spring.datasource.url=jdbc:h2:mem:songsdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.user=sa
spring.datasource.password=password
spring.datasource.config.base.package=es.usj.androidapps
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.trace=false
spring.h2.console.settings.web-allow-others=false
microservice.title=Songs Service
microservice.description=Songs Service for the individual android assessment
microservice.base.package=es.usj.androidapps
spring.sql.init.mode=always